### PR TITLE
Disable client-side validation on setRequiredIndicatorVisible()

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #4077

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 15 of 16 files at r1.
Review status: 15 of 16 files reviewed at latest revision, all discussions resolved.

---

*[pom.xml, line 72 at r1](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77#-LD5q9Th-aQWpCbdi4jw:-LD5q9Th-aQWpCbdi4jx:b-igzrs6) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/08bfd4d4f64af7ebe221fcb422ba41e2a9140937/pom.xml#L72)):*
> ```XML
>             <artifactId>hibernate-validator</artifactId>
>             <version>6.0.1.Final</version>
>         </dependency>
> ```

Where do we use hibernate? Also this is now a dependency both in dependencies and in runTests profile.

---

*[src/main/java/com/vaadin/flow/component/textfield/PasswordField.java, line 33 at r1](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77#-LD5qoKY6Uc-qqLfn2h-:-LD5qoKY6Uc-qqLfn2h0:b5zzjmk) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/08bfd4d4f64af7ebe221fcb422ba41e2a9140937/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java#L33)):*
> ```Java
>  * @author Vaadin Ltd.
>  */
> @JavaScript("frontend://textConnector.js")
> ```

Could these be run only when set requiredIndicatorVisible is set to true the first time?
A bit like we have in [Dialog](https://github.com/vaadin/vaadin-dialog-flow/blob/436d5a54d078ec99edb0e00d99cbecf45ff55425/src/main/java/com/vaadin/flow/component/dialog/Dialog.java#L262)

---

*[src/main/java/com/vaadin/flow/component/textfield/RequiredValidaitonUtil.java, line 28 at r1](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77#-LD5qb8V76kv-Sgn9Una:-LD5qb8V76kv-Sgn9Unb:b-ddvqwp) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/08bfd4d4f64af7ebe221fcb422ba41e2a9140937/src/main/java/com/vaadin/flow/component/textfield/RequiredValidaitonUtil.java#L28)):*
> ```
> RequiredValidaitonUtil
> ```
Typo should be: RequiredValidationUtil

---

*[src/test/java/com/vaadin/flow/component/textfield/tests/AbstractRequiredValidationPage.java, line 52 at r1](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77#-LD5sCHw1e5hK2XwOx_e:-LD5sCHx-KA6NccKfwpE:beilbpf) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/08bfd4d4f64af7ebe221fcb422ba41e2a9140937/src/test/java/com/vaadin/flow/component/textfield/tests/AbstractRequiredValidationPage.java#L52)):*
> ```
> setRequied
> ```
Typo: setRequired

---

*[src/test/java/com/vaadin/flow/component/textfield/tests/Entity.java, line 38 at r1](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77#-LD5ogD-26feos1ylZ-_:-LD5ogD-26feos1ylZ-a:b-d0wxhj) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/08bfd4d4f64af7ebe221fcb422ba41e2a9140937/src/test/java/com/vaadin/flow/component/textfield/tests/Entity.java#L38)):*
> ```Java
>     }
> 
> }
> ```

new line

---

*[src/test/java/com/vaadin/flow/component/textfield/tests/MainView.java, line 58 at r1](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77#-LD5oc8u5lPbaN-Rn-dY:-LD5oc8u5lPbaN-Rn-dZ:bhxzjb5) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/08bfd4d4f64af7ebe221fcb422ba41e2a9140937/src/test/java/com/vaadin/flow/component/textfield/tests/MainView.java#L58)):*
> ```Java
>         // b.forField(name)
>         // .withValidator(a -> a != null && !a.isEmpty(), "eeeeeee")
>         // .bind("name");
> ```

drop commented out code.

---

*[src/test/java/com/vaadin/flow/component/textfield/tests/MainView.java, line 79 at r1](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77#-LD5oZ3DC2eDoApVx3ID:-LD5oZ3DC2eDoApVx3IE:b-d0wxhj) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/08bfd4d4f64af7ebe221fcb422ba41e2a9140937/src/test/java/com/vaadin/flow/component/textfield/tests/MainView.java#L79)):*
> ```Java
>     }
> 
> }
> ```

new line

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77)*

**Comment by denis-anisimov** [comment]
Review status: 15 of 16 files reviewed at latest revision, 7 unresolved discussions.

---

*[pom.xml, line 72 at r1](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77#-LD5q9Th-aQWpCbdi4jw:-LD5tbiS1DDgmCUBngkn:b-exula3) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/08bfd4d4f64af7ebe221fcb422ba41e2a9140937/pom.xml#L72)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Where do we use hibernate? Also this is now a dependency both in dependencies and in runTests profile.
</blockquote></details>

Right, should be inside `runTests` profile only.
It's not hibernate. It's validation implementation for JSR-303 provided by hibernate.
Done.

---

*[src/main/java/com/vaadin/flow/component/textfield/PasswordField.java, line 33 at r1](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77#-LD5qoKY6Uc-qqLfn2h-:-LD5u2uQCZHOhT6Tuwof:bi70ows) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/08bfd4d4f64af7ebe221fcb422ba41e2a9140937/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java#L33)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

Could these be run only when set requiredIndicatorVisible is set to true the first time?
A bit like we have in [Dialog](https://github.com/vaadin/vaadin-dialog-flow/blob/436d5a54d078ec99edb0e00d99cbecf45ff55425/src/main/java/com/vaadin/flow/component/dialog/Dialog.java#L262)
</blockquote></details>

In reality the logic is executed only once on the client side. Because it checks whether it has been already executed.
I prefer do this on the client side instead of having a flag on the server side. It's more reliable since the server side is just a server side face for the client side.

But I think it may be done on the server side as well.
I will do that.

---

*[src/main/java/com/vaadin/flow/component/textfield/RequiredValidaitonUtil.java, line 28 at r1](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77#-LD5qb8V76kv-Sgn9Una:-LD5unO--cPVAcv4L7hf:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/08bfd4d4f64af7ebe221fcb422ba41e2a9140937/src/main/java/com/vaadin/flow/component/textfield/RequiredValidaitonUtil.java#L28)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> ```
> RequiredValidaitonUtil
> ```
Typo should be: RequiredValidationUtil
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/textfield/tests/AbstractRequiredValidationPage.java, line 52 at r1](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77#-LD5sCHw1e5hK2XwOx_e:-LD5uv6W2IxNTSVo1rM1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/08bfd4d4f64af7ebe221fcb422ba41e2a9140937/src/test/java/com/vaadin/flow/component/textfield/tests/AbstractRequiredValidationPage.java#L52)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

> ```
> setRequied
> ```
Typo: setRequired
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/textfield/tests/Entity.java, line 38 at r1](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77#-LD5ogD-26feos1ylZ-_:-LD5uyw1EA3uOJZ0XQVF:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/08bfd4d4f64af7ebe221fcb422ba41e2a9140937/src/test/java/com/vaadin/flow/component/textfield/tests/Entity.java#L38)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/textfield/tests/MainView.java, line 58 at r1](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77#-LD5oc8u5lPbaN-Rn-dY:-LD5v8wJEm5fuOmLao-T:b43k9i9) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/08bfd4d4f64af7ebe221fcb422ba41e2a9140937/src/test/java/com/vaadin/flow/component/textfield/tests/MainView.java#L58)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

drop commented out code.
</blockquote></details>

The whole class is a leftover from the bug verification.
Removed.

---

*[src/test/java/com/vaadin/flow/component/textfield/tests/MainView.java, line 79 at r1](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77#-LD5oZ3DC2eDoApVx3ID:-LD5vGFB1jd1rU8UBrna:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/08bfd4d4f64af7ebe221fcb422ba41e2a9140937/src/test/java/com/vaadin/flow/component/textfield/tests/MainView.java#L79)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77)*

**Comment by denis-anisimov** [comment]
Review status: 15 of 16 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/textfield/PasswordField.java, line 33 at r1](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77#-LD5qoKY6Uc-qqLfn2h-:-LD5vSoODPRzhByiRpbS:b-jon4kl) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/08bfd4d4f64af7ebe221fcb422ba41e2a9140937/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java#L33)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

In reality the logic is executed only once on the client side. Because it checks whether it has been already executed.
I prefer do this on the client side instead of having a flag on the server side. It's more reliable since the server side is just a server side face for the client side.

But I think it may be done on the server side as well.
I will do that.

</blockquote></details>

Ah, we are talking about different things. But anyway....

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77)*

**Comment by denis-anisimov** [comment]
Review status: 4 of 15 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/main/java/com/vaadin/flow/component/textfield/PasswordField.java, line 33 at r1](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77#-LD5qoKY6Uc-qqLfn2h-:-LD5x5oh5mt6P_mn2Yp4:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/08bfd4d4f64af7ebe221fcb422ba41e2a9140937/src/main/java/com/vaadin/flow/component/textfield/PasswordField.java#L33)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Ah, we are talking about different things. But anyway....
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77)*

**Comment by caalador** [comment]
Reviewed 1 of 17 files at r1, 11 of 13 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/77)*

**Pull request merged**
