### PR TITLE
Update generated code for TextField, TextArea and PasswordField

### PR DESCRIPTION
**Pull request by gilberto-torrezan**
Remove hasValue method and add HasValue mixin interface at the generate
class level.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/29)

### CODE REVIEW

**Comment by caalador** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/29)*

**Comment by pleku** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/29#-KzStqpCfM8ZUHwzpHiE:-KzStqpDE_B-2fA5cDBE:b-459y2i) (no related file):*
Please remove the unnecessary synchronizations for it too, I'm not sure if one is present for `PasswordField` too

---

*[src/main/java/com/vaadin/ui/textfield/TextArea.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/29#-KzStu1z1jMCwj9H9Del:-KzStu1z1jMCwj9H9Dem:b-4hbdzr) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/0555ef3b00a4186b8117d703cac123c899a5dd6a/src/main/java/com/vaadin/ui/textfield/TextArea.java#L33)):*
> ```Java
>      */
>     public TextArea() {
>         getElement().synchronizeProperty("hasValue", "value-changed");
> ```

Please remove this

---

*[src/main/java/com/vaadin/ui/textfield/TextField.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/29#-KzSu3BxCHe4naocQTxz:-KzSu3BxCHe4naocQTy-:byp18fd) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/0555ef3b00a4186b8117d703cac123c899a5dd6a/src/main/java/com/vaadin/ui/textfield/TextField.java#L33)):*
> ```Java
>      */
>     public TextField() {
>         getElement().synchronizeProperty("hasValue", "value-changed");
> ```

Remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/29)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/29#-KzStqpCfM8ZUHwzpHiE:-KzSvWLsLYVckkWYRFtE:b-3v18a) (no related file):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please remove the unnecessary synchronizations for it too, I'm not sure if one is present for `PasswordField` too
</blockquote></details>

PasswordField should have overridden accessors for `value` . They also should be removed,

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/29)*

**Comment by gilberto-torrezan** [comment]
Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/29#-KzStqpCfM8ZUHwzpHiE:-KzSxfYEPxb1CbdGXWfO:bx4nh62) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

PasswordField should have overridden accessors for `value` . They also should be removed,
</blockquote></details>

Done and done.

---

*[src/main/java/com/vaadin/ui/textfield/TextArea.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/29#-KzStu1z1jMCwj9H9Del:-KzSxlgC8XEAE4hnG05A:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/0555ef3b00a4186b8117d703cac123c899a5dd6a/src/main/java/com/vaadin/ui/textfield/TextArea.java#L33)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Please remove this
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/ui/textfield/TextField.java, line 33 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/29#-KzSu3BxCHe4naocQTxz:-KzSxmdXE3YjRl9U1ESL:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/0555ef3b00a4186b8117d703cac123c899a5dd6a/src/main/java/com/vaadin/ui/textfield/TextField.java#L33)):*
<details><summary><i>Previously, pleku (Pekka Hyvönen) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/29)*

**Comment by denis-anisimov** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/29)*

**Pull request merged**
