### PR TITLE
Use recent text-field component version and create TextArea component

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fix for #20

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/25)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/25)*

**Comment by denis-anisimov** [comment]
The build fails because required Flow snapshot version is not yet available.
Should be rebuild one it's published.

**Comment by gilberto-torrezan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/25)*

**Comment by caalador** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/25)*

**Pull request merged**
