### PR TITLE
Add value change mode to components.

### PR DESCRIPTION
**Pull request by SomeoneToIgnore**
Requires https://github.com/vaadin/flow/pull/3420 to work.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/44)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/test/java/com/vaadin/flow/component/textfield/demo/HasValueChangeModeButtonProvider.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/44#-L4-VtSnTCOsPfc3mbuJ:-L4-VtSnTCOsPfc3mbuK:b-jpnh1t) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/319b2b6f82b638a061952d75d8fc9e2f8a7ddca1/src/test/java/com/vaadin/flow/component/textfield/demo/HasValueChangeModeButtonProvider.java#L22)):*
> HasValueChangeModeButtonProvider

Is it provider for `HasValueChangeModeButton`?
or it has `ValueChangeModeButtonProvider`?

This pattern with `has` introduced by Google makes the names terrible.
Would be good to make it more convenient in the production code but since this is just a demo may be it's fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/44)*

**Comment by SomeoneToIgnore** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/test/java/com/vaadin/flow/component/textfield/demo/HasValueChangeModeButtonProvider.java, line 22 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/44#-L4-VtSnTCOsPfc3mbuJ:-L4-qxzQr_93ZkZApQTw:b-eqlmkf) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/319b2b6f82b638a061952d75d8fc9e2f8a7ddca1/src/test/java/com/vaadin/flow/component/textfield/demo/HasValueChangeModeButtonProvider.java#L22)):*
> ValueChangeModeButtonProvider

Used that one, thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/44)*

**Comment by SomeoneToIgnore** [comment]
Build is green.

---

Review status: 4 of 11 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/44#-:-L410OlR1R4IDBc3LOPl:bnz2s7e)*

**Comment by denis-anisimov** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/44)*

**Pull request merged**
