### PR TITLE
Rename package com.vaadin.ui to com.vaadin.flow.component

### PR DESCRIPTION
**Pull request by denis-anisimov**
Part of the #3032

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/39)

### CODE REVIEW

**Comment by pleku** [comment]
Review status: 0 of 20 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39#-L0LGsc2E0HKy_8tjZ2d:-L0LGsc2E0HKy_8tjZ2e:btffg9c) (no related file):*
Blocking until we have decision between having the components in same package or splitting the components into different names e.g. `..component.textfield.TextField` `..component.textarea.TextArea` and `..component.passwordfield.PasswordField` .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39)*

**Comment by pleku** [comment]
:lgtm:

---

Reviewed 40 of 40 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39#-:-L0O7bfHAK0iVAoykRUs:bnfp4nl)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/test/java/com/vaadin/flow/component/textfield/demo/PasswordFieldView.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39#-L0OUSztKlBfXHSkG9AO:-L0OUSztKlBfXHSkG9AP:baw1n6b) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/7db3e9ec0daa7046a1ffbb8e6a4183e17c2aaeca/src/test/java/com/vaadin/flow/component/textfield/demo/PasswordFieldView.java#L23)):*
> ```Java
> import com.vaadin.router.Route;
> import com.vaadin.ui.common.HtmlImport;
> import com.vaadin.ui.html.Div;
> ```

oh.. those should be changed also.. i think..

---

*[src/test/java/com/vaadin/flow/component/textfield/demo/TextAreaView.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39#-L0OUZqwMQUT2AEpdTmG:-L0OUZqwMQUT2AEpdTmH:b-rkz2ij) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/7db3e9ec0daa7046a1ffbb8e6a4183e17c2aaeca/src/test/java/com/vaadin/flow/component/textfield/demo/TextAreaView.java#L23)):*
> ```Java
> import com.vaadin.router.Route;
> import com.vaadin.ui.common.HtmlImport;
> import com.vaadin.ui.html.Div;
> ```

same here..

---

*[src/test/java/com/vaadin/flow/component/textfield/demo/TextFieldView.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39#-L0OUcgpVDsuQdvkueKU:-L0OUcgpVDsuQdvkueKV:bji28bi) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/7db3e9ec0daa7046a1ffbb8e6a4183e17c2aaeca/src/test/java/com/vaadin/flow/component/textfield/demo/TextFieldView.java#L23)):*
> ```Java
> import com.vaadin.router.Route;
> import com.vaadin.ui.common.HtmlImport;
> import com.vaadin.ui.html.Div;
> ```

and here

---

*[src/test/java/com/vaadin/flow/component/textfield/tests/PasswordFieldPage.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39#-L0OUgFTDfqOy0-LuXOO:-L0OUgFTDfqOy0-LuXOP:be02rrk) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/7db3e9ec0daa7046a1ffbb8e6a4183e17c2aaeca/src/test/java/com/vaadin/flow/component/textfield/tests/PasswordFieldPage.java#L21)):*
> ```Java
> import com.vaadin.router.Route;
> import com.vaadin.ui.button.Button;
> import com.vaadin.ui.html.Div;
> ```

and here...

---

*[src/test/java/com/vaadin/flow/component/textfield/tests/TextFieldPage.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39#-L0OUlhDmXgjRmPnSbKI:-L0OUlhDmXgjRmPnSbKJ:bb7hf91) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/7db3e9ec0daa7046a1ffbb8e6a4183e17c2aaeca/src/test/java/com/vaadin/flow/component/textfield/tests/TextFieldPage.java#L21)):*
> ```Java
> import com.vaadin.router.Route;
> import com.vaadin.ui.button.Button;
> import com.vaadin.ui.html.Div;
> ```

here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/test/java/com/vaadin/flow/component/textfield/demo/PasswordFieldView.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39#-L0OUSztKlBfXHSkG9AO:-L0OY6MDacct_QjlIq5w:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/7db3e9ec0daa7046a1ffbb8e6a4183e17c2aaeca/src/test/java/com/vaadin/flow/component/textfield/demo/PasswordFieldView.java#L23)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

oh.. those should be changed also.. i think..
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/textfield/demo/TextAreaView.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39#-L0OUZqwMQUT2AEpdTmG:-L0OY7HsiDGmHUUxVAcp:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/7db3e9ec0daa7046a1ffbb8e6a4183e17c2aaeca/src/test/java/com/vaadin/flow/component/textfield/demo/TextAreaView.java#L23)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

same here..
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/textfield/demo/TextFieldView.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39#-L0OUcgpVDsuQdvkueKU:-L0OY7fGPrVk9a5CmAkZ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/7db3e9ec0daa7046a1ffbb8e6a4183e17c2aaeca/src/test/java/com/vaadin/flow/component/textfield/demo/TextFieldView.java#L23)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

and here
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/textfield/tests/PasswordFieldPage.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39#-L0OUgFTDfqOy0-LuXOO:-L0OY8DAI6fV7mMEA0X5:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/7db3e9ec0daa7046a1ffbb8e6a4183e17c2aaeca/src/test/java/com/vaadin/flow/component/textfield/tests/PasswordFieldPage.java#L21)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

and here...
</blockquote></details>

Done.

---

*[src/test/java/com/vaadin/flow/component/textfield/tests/TextFieldPage.java, line 21 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39#-L0OUlhDmXgjRmPnSbKI:-L0OY8dthXuUdf_cdovF:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/7db3e9ec0daa7046a1ffbb8e6a4183e17c2aaeca/src/test/java/com/vaadin/flow/component/textfield/tests/TextFieldPage.java#L21)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/test/java/com/vaadin/flow/component/textfield/demo/PasswordFieldView.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39#-L0OUSztKlBfXHSkG9AO:-L0OYYkNBOK4771ciDgM:b-u4ddds) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/7db3e9ec0daa7046a1ffbb8e6a4183e17c2aaeca/src/test/java/com/vaadin/flow/component/textfield/demo/PasswordFieldView.java#L23)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

there must be something wrong with my internet... i cannot see the changes...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39)*

**Comment by denis-anisimov** [comment]
Review status: 15 of 20 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/test/java/com/vaadin/flow/component/textfield/demo/PasswordFieldView.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39#-L0OUSztKlBfXHSkG9AO:-L0OZ4o2t-9hU5HaQWRu:b2s0j53) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/7db3e9ec0daa7046a1ffbb8e6a4183e17c2aaeca/src/test/java/com/vaadin/flow/component/textfield/demo/PasswordFieldView.java#L23)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

there must be something wrong with my internet... i cannot see the changes...
</blockquote></details>

Now there are here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39)*

**Comment by ZheSun88** [comment]
Reviewed 5 of 40 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39)*

**Comment by denis-anisimov** [comment]
Reviewed 26 of 40 files at r1, 14 of 14 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/39)*

**Pull request merged**
