### PR TITLE
Run unit tests using profile where Flow deps have compile scope

### PR DESCRIPTION
**Pull request by denis-anisimov**
Part of #3630

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/75)

### CODE REVIEW

**Comment by ZheSun88** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[pom.xml, line 70 at r2](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/75#-LBuJvYS-R2yR0ISyWWM:-LBuJvYS-R2yR0ISyWWN:b-d1qoou) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/7984fc22c98c5ae6bd49b9086d00946bd8a0d195/pom.xml#L70)):*
> ```XML
>                 <dependency>
>                     <groupId>com.vaadin</groupId>
>                     <artifactId>flow-data</artifactId>
> ```

what is the reason to leave `flow-date` here?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/75)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 70 at r2](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/75#-LBuJvYS-R2yR0ISyWWM:-LBuNxRf220QIsvFhMCC:bcgd273) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/7984fc22c98c5ae6bd49b9086d00946bd8a0d195/pom.xml#L70)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

what is the reason to leave `flow-date` here?
</blockquote></details>

Broken build.
Don't ask why. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/75)*

**Comment by ZheSun88** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 70 at r2](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/75#-LBuJvYS-R2yR0ISyWWM:-LBuWYc63TFWAIoxTW0I:bwd9sqd) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/7984fc22c98c5ae6bd49b9086d00946bd8a0d195/pom.xml#L70)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Broken build.
Don't ask why. 
</blockquote></details>

okay, in this case, should we just remove the `flow-data` dependency from the parent pom ?
I really don't know why only this dependency is not inherited from there..

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/75)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 70 at r2](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/75#-LBuJvYS-R2yR0ISyWWM:-LBucHK08lNNU0FLRgo1:b2qy5ym) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/7984fc22c98c5ae6bd49b9086d00946bd8a0d195/pom.xml#L70)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

okay, in this case, should we just remove the `flow-data` dependency from the parent pom ?
I really don't know why only this dependency is not inherited from there..
</blockquote></details>

Me neither.

May be we need to remove `flow-data`.
But this won't affect anyhow this PR and all others with this change.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/75)*

**Comment by ZheSun88** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 70 at r2](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/75#-LBuJvYS-R2yR0ISyWWM:-LBufUEk7eOOoYn3FzTJ:bl7kq5m) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/7984fc22c98c5ae6bd49b9086d00946bd8a0d195/pom.xml#L70)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Me neither.

May be we need to remove `flow-data`.
But this won't affect anyhow this PR and all others with this change.
</blockquote></details>

I will resolve this comment for now, but i am not sure i should merge this PR or not, as i don't know why it doesn't work. I will do some research firstly. I hope that is fine for you.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/75)*

**Comment by ZheSun88** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/75#-:-LCSTK7U8qvt1R68nDkT:bnfp4nl)*

**Pull request merged**
