### PR TITLE
Add test cases for null value, and remove unneeded overriding (Fixes #28)

### LINKED ISSUE #28: Don't accept setValue(null)
Right now, `textField.setValue(null)` and `textField.setValue("")` lead to exactly the same result both from the perspective of the user and for the return value of `getValue()`. This is confusing.

Suggested to instead make `TextField` work in the same way as in FW8, i.e. throwing an unchecked exception (currently not implemented in V10 and never returning `null` from `getValue()` (currently implemented in V10).

### PR DESCRIPTION
**Pull request by asashour**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-text-field-flow/37)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L-jqfGKJq9Sj8m9Wk59:-L-jqfGKJq9Sj8m9Wk5A:b-g5q25x) (no related file):*
There is an open question: should this go into the components Generator instead of making boilerplate changes for every component.
General FW8 behavior for `HasValue` : don't accept `null`s.
Which means that this is the generic case which may be implemented on the component generator level.
Component configuration can be changed in the way to allow accepting `null` for some specific cases.

@legioth , what do you think ? Should it be done on the component generator level ?

---

*[src/main/java/com/vaadin/ui/textfield/PasswordField.java, line 128 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L-jqNKk21JsD44pKBCD:-L-jqNKk21JsD44pKBCE:b-gbgzwv) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/85e87bbb23ca4cd5c53a069ce23065ad5879a963/src/main/java/com/vaadin/ui/textfield/PasswordField.java#L128)):*
> Objects.requireNonNull(value, "value cannot be null");
>         super.setValue(value);

May be improved: 
`super.setValue(Objects.requireNonNull(value, "value cannot be null"));`

---

*[src/main/java/com/vaadin/ui/textfield/TextArea.java, line 146 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L-jqYZ03ZlcDr1f65Ue:-L-jqYZ03ZlcDr1f65Uf:b-gbgzwv) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/85e87bbb23ca4cd5c53a069ce23065ad5879a963/src/main/java/com/vaadin/ui/textfield/TextArea.java#L146)):*
> Objects.requireNonNull(value, "value cannot be null");
>         super.setValue(value);

May be improved: 
`super.setValue(Objects.requireNonNull(value, "value cannot be null"));`

---

*[src/main/java/com/vaadin/ui/textfield/TextField.java, line 146 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L-jq_BER32lhWLhk1xB:-L-jq_BER32lhWLhk1xC:b-a8jfnp) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/85e87bbb23ca4cd5c53a069ce23065ad5879a963/src/main/java/com/vaadin/ui/textfield/TextField.java#L146)):*
> Objects.requireNonNull(value, "value cannot be null");
>         super.setValue(value);


May be improved: 
`super.setValue(Objects.requireNonNull(value, "value cannot be null"));`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L-jqfGKJq9Sj8m9Wk59:-L-jvtnXaheuoJQhShGG:b-bt848j) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

There is an open question: should this go into the components Generator instead of making boilerplate changes for every component.
General FW8 behavior for `HasValue` : don't accept `null`s.
Which means that this is the generic case which may be implemented on the component generator level.
Component configuration can be changed in the way to allow accepting `null` for some specific cases.

@legioth , what do you think ? Should it be done on the component generator level ?
</blockquote></details>

is this PR the fix of the null check you mentioned https://github.com/vaadin/flow/pull/3074

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37)*

**Comment by Legioth** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L-jqfGKJq9Sj8m9Wk59:-L-k3ihH1AnW0zBlT7b9:bnh2oyv) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

is this PR the fix of the null check you mentioned https://github.com/vaadin/flow/pull/3074
</blockquote></details>

Not accepting `null` is a thing only for components where the value is `String` or some collection type.

Components such as `ComboBox` or `DatePicker` should accept `null` since there is no other `<T>` or `LocalDate` that represents an empty value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37)*

**Comment by asashour** [comment]
Review status: 3 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L-jqfGKJq9Sj8m9Wk59:-L-k5yLOFFtTOAYWqSjw:bkmr7cl) (no related file):*
<details><summary><i>Previously, Legioth (Leif Åstrand) wrote…</i></summary><blockquote>

Not accepting `null` is a thing only for components where the value is `String` or some collection type.

Components such as `ComboBox` or `DatePicker` should accept `null` since there is no other `<T>` or `LocalDate` that represents an empty value.
</blockquote></details>

From what I understand, we don't allow `null` if `getEmptyValue()` returns "".

---

*[src/main/java/com/vaadin/ui/textfield/PasswordField.java, line 128 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L-jqNKk21JsD44pKBCD:-L-k7eHQV9qbgyVyOaKo:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/85e87bbb23ca4cd5c53a069ce23065ad5879a963/src/main/java/com/vaadin/ui/textfield/PasswordField.java#L128)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Objects.requireNonNull(value, "value cannot be null");
>         super.setValue(value);

May be improved: 
`super.setValue(Objects.requireNonNull(value, "value cannot be null"));`
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/ui/textfield/TextArea.java, line 146 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L-jqYZ03ZlcDr1f65Ue:-L-k7ehZGLvITG9WHh8y:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/85e87bbb23ca4cd5c53a069ce23065ad5879a963/src/main/java/com/vaadin/ui/textfield/TextArea.java#L146)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Objects.requireNonNull(value, "value cannot be null");
>         super.setValue(value);

May be improved: 
`super.setValue(Objects.requireNonNull(value, "value cannot be null"));`
</blockquote></details>

Done.

---

*[src/main/java/com/vaadin/ui/textfield/TextField.java, line 146 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L-jq_BER32lhWLhk1xB:-L-k7f84-kuTWJksCwWk:b-896fix) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/85e87bbb23ca4cd5c53a069ce23065ad5879a963/src/main/java/com/vaadin/ui/textfield/TextField.java#L146)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> Objects.requireNonNull(value, "value cannot be null");
>         super.setValue(value);


May be improved: 
`super.setValue(Objects.requireNonNull(value, "value cannot be null"));`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37)*

**Comment by denis-anisimov** [comment]
Review status: 3 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L-jqfGKJq9Sj8m9Wk59:-L-kRWKT2fNjP3KGyYEk:by8jr3i) (no related file):*
> is this PR the fix of the null check you mentioned vaadin/flow#3074

So why do we need this PR if there is already such thing implemented in the generator ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37)*

**Comment by denis-anisimov** [comment]
Review status: 3 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L-jqfGKJq9Sj8m9Wk59:-L-kRm27dl4ur6BuIWAr:b-3rngoz) (no related file):*
>From what I understand, we don't allow null if getEmptyValue() returns "".

You can't check what does `getEmptyValue()` return without runtime.

I would say it should check the data type of the component (the `T` in `HasValue<T>` )
If it's a `String` or a collection then it should not accept `null`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37)*

**Comment by asashour** [comment]
Review status: 3 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L-jqfGKJq9Sj8m9Wk59:-L-kSM2m8lcpp8rgJ8aj:b9wpvdb) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>From what I understand, we don't allow null if getEmptyValue() returns "".

You can't check what does `getEmptyValue()` return without runtime.

I would say it should check the data type of the component (the `T` in `HasValue<T>` )
If it's a `String` or a collection then it should not accept `null`.
</blockquote></details>

What was implemented in the generator is `getReturnValue()` to return `getEmptyValue()` if property is `null`, this applies to all components, e.g. `ComboBox`, `DatePicker`, 'TextField' (the three examples have String value type)

However, `ComboBox` and `DatePicker` should accept `null`, and so `getEmptyString()` was not overridden to return "".

But the `TextField` (and siblings) should not accept `null` and have overridden `getEmptyString()` to return "", and they also should prevent setting null value.

If the `getEmptyString()` is null  or "", could be determined by the generated, then we should change the generator accordingly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37)*

**Comment by asashour** [comment]
Review status: 3 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L-jqfGKJq9Sj8m9Wk59:-L-kVRnjpt_rU4nSyMHf:b-us47zj) (no related file):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

What was implemented in the generator is `getReturnValue()` to return `getEmptyValue()` if property is `null`, this applies to all components, e.g. `ComboBox`, `DatePicker`, 'TextField' (the three examples have String value type)

However, `ComboBox` and `DatePicker` should accept `null`, and so `getEmptyString()` was not overridden to return "".

But the `TextField` (and siblings) should not accept `null` and have overridden `getEmptyString()` to return "", and they also should prevent setting null value.

If the `getEmptyString()` is null  or "", could be determined by the generated, then we should change the generator accordingly.
</blockquote></details>

Just a moment, I will revise what I just said.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37)*

**Comment by asashour** [comment]
Review status: 3 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L-jqfGKJq9Sj8m9Wk59:-L-kxQHNcMFuZtGlTmAR:b8582ow) (no related file):*
<details><summary><i>Previously, asashour (Ahmed Ashour) wrote…</i></summary><blockquote>

Just a moment, I will revise what I just said.
</blockquote></details>

Well, there is a PR https://github.com/vaadin/flow/pull/3114 in component generator for handling string values.

After it is merged, I will change this PR to remove the redundant methods in `TextField` and siblings.

Further PRs should change the component generator to handle String or Collection in typed components.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37)*

**Comment by asashour** [comment]
Since the needed change was done in generator, thanks to Denis input, the scope of this PR is now:

- Remove unneeded `getEmptyValue()` for `TextField`
- Add test cases for setting null values
- Update `GeneratedTextField`

**Comment by asashour** [comment]
Two points observed:

- `TextAreaIT`.`maxHeight` and `minHeight` fail also locally with `master`, which is not related to this PR changes.
- TeamCity for this repository always ask for login, and not using "default guest user" like other repositories.

**Comment by denis-anisimov** [comment]
You should rebase this PR manually.
There are many conflicts.

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/main/java/com/vaadin/ui/textfield/GeneratedVaadinPasswordField.java, line 32 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L16Hyct3NhDYndHMA9I:-L16Hyct3NhDYndHMA9J:b-gocvdg) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/2009e7cf172f7e3757f832219583d1c1dd61d13f/src/main/java/com/vaadin/ui/textfield/GeneratedVaadinPasswordField.java#L32)):*
>  * {@code }
>  * <code>html &lt;vaadin-password-field label=&quot;Password&quot;&gt; &lt;/vaadin-password-field&gt; {@code }</code>

Is this regenerated code ?

---

*[src/main/java/com/vaadin/ui/textfield/GeneratedVaadinTextArea.java, line 520 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L16I3re2i2Kl7bpwdnq:-L16I3re2i2Kl7bpwdnr:b-js4oig) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/b183a7d657a69e074c5523b1f962b7344ef2af2b/src/main/java/com/vaadin/ui/textfield/GeneratedVaadinTextArea.java#L520)):*
> public String getValue() {
>         String value = getElement().getProperty("value");
>         return value == null ? getEmptyValue() : value;
>     }

Is this class regenerated ?

---

*[src/main/java/com/vaadin/ui/textfield/GeneratedVaadinTextField.java, line 519 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L16I9fgF6gph972oXmk:-L16I9fgF6gph972oXml:bizha71) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/b183a7d657a69e074c5523b1f962b7344ef2af2b/src/main/java/com/vaadin/ui/textfield/GeneratedVaadinTextField.java#L519)):*
> public String getValue() {
>         String value = getElement().getProperty("value");
>         return value == null ? getEmptyValue() : value;
>     }

Is it regenerated ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-:-L16IPgySv5lyHOjaOCK:b-70b7q2)*

**Comment by asashour** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main/java/com/vaadin/ui/textfield/GeneratedVaadinPasswordField.java, line 32 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L16Hyct3NhDYndHMA9I:-L1C63e_OJaPXCQSUKJe:ba58flv) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/2009e7cf172f7e3757f832219583d1c1dd61d13f/src/main/java/com/vaadin/ui/textfield/GeneratedVaadinPasswordField.java#L32)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

>  * {@code }
>  * <code>html &lt;vaadin-password-field label=&quot;Password&quot;&gt; &lt;/vaadin-password-field&gt; {@code }</code>

Is this regenerated code ?
</blockquote></details>

Yes, Generated java files are updated from Flow `master`.

---

*[src/main/java/com/vaadin/ui/textfield/GeneratedVaadinTextArea.java, line 520 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L16I3re2i2Kl7bpwdnq:-L1C6BOhGpCxBT9inBDt:budt7xj) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/b183a7d657a69e074c5523b1f962b7344ef2af2b/src/main/java/com/vaadin/ui/textfield/GeneratedVaadinTextArea.java#L520)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> public String getValue() {
>         String value = getElement().getProperty("value");
>         return value == null ? getEmptyValue() : value;
>     }

Is this class regenerated ?
</blockquote></details>

Yes, Generated java files are updated from Flow `master`.

---

*[src/main/java/com/vaadin/ui/textfield/GeneratedVaadinTextField.java, line 519 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-L16I9fgF6gph972oXmk:-L1C6EYTk0EftfkMxeEV:ba58flv) ([raw file](https://github.com/vaadin/vaadin-text-field-flow/blob/b183a7d657a69e074c5523b1f962b7344ef2af2b/src/main/java/com/vaadin/ui/textfield/GeneratedVaadinTextField.java#L519)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> public String getValue() {
>         String value = getElement().getProperty("value");
>         return value == null ? getEmptyValue() : value;
>     }

Is it regenerated ?
</blockquote></details>

Yes, Generated java files are updated from Flow `master`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37)*

**Comment by asashour** [comment]
I am not sure what should be done in Generated components javadoc errors.

**Comment by denis-anisimov** [comment]
Reviewed 15 of 18 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37)*

**Comment by ZheSun88** [comment]
the build fails on test class. maybe you should rebase the master as it has been fixed.. or just correct the `By` word import.

**Comment by ZheSun88** [comment]
Reviewed 12 of 18 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37)*

**Comment by SomeoneToIgnore** [comment]
:lgtm:

---

Reviewed 12 of 18 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-text-field-flow/37#-:-L2eM-x08WdXhccLY0b-:bnfp4nl)*

**Pull request merged**
